[package]
name = "kite-crawler"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12"
actix-web = "2"
tokio = { version = "0.2", features = ["full"] }