[package]
name = "kite-crawler"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Custom component
kite-protocol = { version = "0.1", path = "../kite-protocol", branch = "develop" }

# Common tools
rand = "0.7"
lazy_static = "1.4"
regex = "1"
thiserror = "1"
chrono = "0.4"

# Network related
scraper = "0.12"
awc = { version = "1.0.1", features = ["rustls"] }
actix-http = "1"
actix-rt = "1.1"
tokio = { version = "0.2", features = ["full"] }

# Database
sled = "0.34"
bincode = "1.3"

# Encryption and code
aes = "0.4"
base64 = "0.12"
block-modes = "0.5"
urlencoding = "1.0"