[package]
name = "kite-crawler"
version = "0.1.0"
authors = ["sunnysab <sunnysab@yeah.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kite-protocol = { version = "0.1", path = "../kite-protocol", branch = "develop" }

rand = "0.7"
lazy_static = "1.4"
regex = "1"
thiserror = "1"
chrono = "0.4"

scraper = "0.12"
awc = "1.0.1"
actix-rt = "1.1"
tokio = { version = "0.2", features = ["full"] }