[agent]
# Agent name, identify agent for server
name = "localhost"
# Db cache name. we will create a directory to stored sessions automatically.
db = "kite-cache"
# Fetch over the given http/https/socks5 proxy
# proxy = "http://localhost:8888/"

[server]
# Message host address.
addr = "localhost:8443"
# Max connections to server
conn = 5